services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: teampay_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - teampay

  nginx:
    image: nginx:alpine
    container_name: teampay_nginx
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teampay

  mysql:
    image: mysql:8.0
    container_name: teampay_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: teampay
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: teampay
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - teampay

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: teampay_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9001:80"
    networks:
      - teampay

  redis:
    image: redis:alpine
    container_name: teampay_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - teampay

  queue:
    build:
      context: .
      dockerfile: dockerfile
    container_name: teampay_queue
    restart: unless-stopped
    command: php artisan queue:work
    volumes:
      - .:/var/www
    depends_on:
      - app
      - redis
    networks:
      - teampay

networks:
  teampay:

volumes:
  mysql_data:
